server:
  port: 9001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mes_db
    #url: jdbc:postgresql://192.168.1.142:5432/mes_db
    username: mes_user
    password: mes_pwd

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
       
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        

#logging:
  level:
    org:
      hibernate:
        type: trace
